### PR TITLE
AARCH64 >= armv8.3-a supports pointer authentication. If this feature is

### PR DESCRIPTION
**Pull request by JulianMarcusSchroeder**
enabled it modifies the previously unused upper address bits in apointer. The affected bits need to be cleared in order for stacktrace to work.

### CODE REVIEW

**Comment by alk** [comment]
Thanks for the patch. This is great. But why bother with asm? We're not that performance-sensitive in this code, so we can simply clear those top bits in portable C++ and be done?

**Comment by alk** [comment]
Actually, asm probably makes sense. This way with _only_ strip if computer is running with pointer auth supported _and_ enabled.

But looking closer I am now confused why asm part is not  under __aarch64__. We don't want x86 compilers to see this, right ?

**Comment by alk** [comment]
Also you sure we require hard-coding x30 register? Can we somehow detect if arm 8.3 is enabled and then use proper XPACI instruction and let compiler choose register.

**Comment by JulianMarcusSchroeder** [comment]
The xpaclri instruction is for the LR register (x30) only. It doesn't work for other registers.
I'll  add the __aarch64__  wrapper. I spaced out on that one ;-).

**Comment by alk** [comment]
Applied. Thanks. Note, I had to modify commit message to add subject line, but the commit is 100% yours otherwise.

**Pull request closed without merging**
