### PR TITLE
Add MPICH environment detection

### PR DESCRIPTION
**Pull request by raffenet**
@artpol84 suggested I add MPICH support along with his PMIX and OMPI changes in #1263.

### CODE REVIEW

**Comment by artpol84** [comment]
@raffenet looks great! Thank you.

**Comment by alk** [comment]
Nice and thanks a lot. For patch itself, it does look like you forgot to add actual invokation of testMPICH to test's main function. Or did I miss anything?

**Comment by raffenet** [comment]
> Nice and thanks a lot. For patch itself, it does look like you forgot to add actual invokation of testMPICH to test's main function. Or did I miss anything?

You are right. Just force pushed a fix. Thanks for catching.

**Comment by alk** [comment]
I see {false, ..stuff.., ..stuff.. ) (round closing brace) in first commit. Please, make sure to at least compile-test your change (and ideally make check as well). Please.

Also it works best for changes like this to be just single combined commit. If your git-fu is strong enough, please consider squashing commits (if not, no big deal).

**Comment by raffenet** [comment]
> I see {false, ..stuff.., ..stuff.. ) (round closing brace) in first commit. Please, make sure to at least compile-test your change (and ideally make check as well). Please.

🤦. Thanks, this latest push is tested with `make; make check` on my laptop. FWIW, I see this failure which I assume is unrelated. (macOS 12.6.8, apple clang 14.0.0)
```
FAIL: tcmalloc_minimal_large_heap_fragmentation_unittest
========================================================

src/tests/large_heap_fragmentation_unittest.cc:57 Check failed: heap_size < 1*1024*1024*1024
FAIL tcmalloc_minimal_large_heap_fragmentation_unittest (exit status: 134)
```
> 
> Also it works best for changes like this to be just single combined commit. If your git-fu is strong enough, please consider squashing commits (if not, no big deal).

Squashed.

**Comment by alk** [comment]
Applied. Thanks a lot!

**Pull request closed without merging**
