### PR TITLE
Misc fix-ups for macOS

### PR DESCRIPTION
**Pull request by barracuda156**
Let’s fix some broken stuff here and there.

1. ARM detection does not work on macOS using existing code:
```
--->  Configuring gperftools
Executing:  cd "/opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_devel_gperftools/gperftools/work/build" && /opt/local/bin/cmake -G "CodeBlocks - Unix Makefiles" -DCMAKE_BUILD_TYPE=MacPorts -DCMAKE_INSTALL_PREFIX="/opt/local" -DCMAKE_INSTALL_NAME_DIR="/opt/local/lib" -DCMAKE_SYSTEM_PREFIX_PATH="/opt/local;/usr" -DCMAKE_C_COMPILER="$CC" -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_OBJC_COMPILER="$CC" -DCMAKE_OBJCXX_COMPILER="$CXX" -DCMAKE_POLICY_DEFAULT_CMP0025=NEW -DCMAKE_POLICY_DEFAULT_CMP0060=NEW -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_COLOR_MAKEFILE=ON -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_MAKE_PROGRAM=/usr/bin/make -DCMAKE_MODULE_PATH="/opt/local/share/cmake/Modules" -DCMAKE_PREFIX_PATH="/opt/local/share/cmake/Modules" -DCMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=ON -DCMAKE_INSTALL_RPATH="/opt/local/lib" -Wno-dev -DBUILD_TESTING:BOOL=OFF -Dgperftools_build_benchmark:BOOL=OFF -Dgperftools_enable_libunwind:BOOL=OFF -DCMAKE_OSX_ARCHITECTURES="arm64" -DCMAKE_CXX_STANDARD=17 -DCMAKE_OSX_DEPLOYMENT_TARGET="14.0" -DCMAKE_OSX_SYSROOT="/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk" /opt/local/var/macports/build/_opt_svacchanda_SonomaPorts_devel_gperftools/gperftools/work/gperftools-2.13 
-- The C compiler identification is AppleClang 15.0.0.15000040
-- The CXX compiler identification is AppleClang 15.0.0.15000040
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test i386
-- Performing Test i386 - Failed
-- Performing Test s390
-- Performing Test s390 - Failed
-- Performing Test PPC64
-- Performing Test PPC64 - Failed
-- Performing Test x86_64
-- Performing Test x86_64 - Failed
-- Performing Test ARM
-- Performing Test ARM - Failed
-- Performing Test FreeBSD
-- Performing Test FreeBSD - Failed
-- Performing Test MINGW
-- Performing Test MINGW - Failed
-- Performing Test LINUX
-- Performing Test LINUX - Failed
-- Performing Test OSX
-- Performing Test OSX - Success
```
Macports has a fix for that, borrow it here, but in a non-invasive way (I guess, current code has been tested at least on some platforms?).

2. PowerPC defines are wrong: there is no `__PPC64__` on macOS.
3. Comments to context variables are inaccurate.

### CODE REVIEW

**Comment by alk** [comment]
Thanks for the patches. Question about:

```
  "uc_mcontext->__ss.__pc")  # OS X (arm64, >=11 [untested])
```

Can you please elaborate 11 thingy? Isn't it that all OS X versions 10.x (i.e. X in OS is roman 10)?

**Comment by barracuda156** [comment]
@alk Support for aarch64 has been introduced in Big Sur, which is macOS 11. You are right, it is not “OS X” strictly speaking, they have dropped X, but it is still used in Apple codebase and elsewhere (CMake has OSX_ARCHITECTURES, GCC has flags for macosx version etc.). So I just thought consistency is preferable over maintaining formal naming. But this can be changed, of course, if you prefer.

**Comment by alk** [comment]
merged. thanks.

**Comment by barracuda156** [comment]
@alk Thank you!

**Pull request merged**
