### PR TITLE
prefetch multi tc_slots from pageheap

### PR DESCRIPTION
**Pull request by flex1988**

### CODE REVIEW

**Comment by flex1988** [comment]
@googlebot I signed it!

**Comment by flex1988** [comment]
@googlebot I fixed it.

**Comment by alk** [comment]
Thanks for patch. Couple things.

*) can you please describe (in commit message) why this is useful thing to do

*) rest of code in this project and c++ file puts '{' braces to be on same line as if/while/else etc. We're using Google C++ style. It won't be right for us to deviate from this. Can you please fix this ?

**Comment by alk** [comment]
Gentle ping on the message above.

**Comment by flex1988** [comment]
> Gentle ping on the message above.

 just seen a todo in docs, and don't have a strong reason to do this, so i will close it

**Pull request closed without merging**
