### PR TITLE
add cpu profiler support for qnx

### PR DESCRIPTION
**Pull request by iDings**
This patch is just work, but the correctness of the profile result is still need to be verifying,  i don't have an another tool or some method to double check the result.  

As discussed in https://github.com/gperftools/gperftools/issues/1429#issuecomment-1728142330, QNX didn't support SIGPROF， and https://github.com/gperftools/gperftools/issues/108#issuecomment-133672208 had a nice explanation about why use SIGALAM(ITIMER_REAL) is not a good way, but for qnx, use ITIMER_REAL as the cpu profiler timer seems
a method to do some profiling about cpu, a.k.a poor man's profiler.

From https://github.com/gperftools/gperftools/issues/108#issuecomment-133672208,  mainly two concerns about ITIMER_REAL

>For ITIMER_REAL, you're getting one tick per "<interval> real-time seconds
consumed".  If you have multiple threads, you then have to "distribute" that
tick to the rest of the threads, and collect data from them.

Qnx support [per-thread signal](https://www.qnx.com/developers/docs/7.0.0/index.html#com.qnx.doc.neutrino.lib_ref/topic/s/sigevent.html#sigevent__SIGEV_SIGNAL_THREAD), so maybe should add use feature like as  [HAVE_LINUX_SIGEV_THREAD_ID](https://github.com/golang/go/issues/14434)

> Note also that use of ITIMER_REAL/SIGALRM will screw up any other uses of
SIGALRM in the process.  

No very sure about if any QNX closed source library use SIGALRM or not， and for user
who want use this cpu profiler on QNX,  need to check SIGALRM usage on their codes.

 Anyway this patch just request for comments, and for some guys want try gperftools cpu profiler on qnx, 
and maybe some QNX masters see this and give some more advises.

### CODE REVIEW

**Comment by alk** [comment]
Hi. Thanks for the patch. My main question is what is the value of this patch? My understanding is qnx already has own cpu profiling tool(s). So why not let people use them?

In principle this change isn't huge, so I could accept it, but it adds some ifdefs. So it is a complexity that might be more hassle then value.

**Comment by alk** [comment]
Also if you still want to proceed with this, please double check that this actually produces useful profiles. Say, simple single threaded programs should work.

**Comment by iDings** [comment]
Update some profiler_unittest result on QNX:

1. single thread: `profiler3_unittest 100 0 profile1_t3.prof` 

```
File: profiler3_unittest
Type: cpu
Showing nodes accounting for 7.02s, 98.87% of 7.10s total
Dropped 3 nodes (cum <= 0.04s)
      flat  flat%   sum%        cum   cum%
     3.44s 48.45% 48.45%      6.99s 98.45%  test_main_thread
     0.70s  9.86% 58.31%      0.70s  9.86%  [libc.so.5]
     0.58s  8.17% 66.48%      2.26s 31.83%  _Printf
     0.45s  6.34% 72.82%      0.45s  6.34%  _Mbtowcx
     0.43s  6.06% 78.87%      0.43s  6.06%  prout
     0.40s  5.63% 84.51%      0.40s  5.63%  __memcpy_isr
     0.26s  3.66% 88.17%      0.26s  3.66%  _Mbtowc
     0.20s  2.82% 90.99%      0.20s  2.82%  __c11_atomic_fetch_xor (inline)
     0.19s  2.68% 93.66%      3.33s 46.90%  snprintf
     0.09s  1.27% 94.93%      0.21s  2.96%  _Putfld
     0.07s  0.99% 95.92%      0.23s  3.24%  _Puttxt
     0.07s  0.99% 96.90%      0.07s  0.99%  {lambda(void*)#1}::_FUN
     0.05s   0.7% 97.61%      0.05s   0.7%  _Litob
     0.05s   0.7% 98.31%      0.05s   0.7%  __memchr_isr
     0.04s  0.56% 98.87%      0.04s  0.56%  _get_arg_num (inline)
         0     0% 98.87%      7.10s   100%  _start
         0     0% 98.87%      7.10s   100%  main
         0     0% 98.87%      0.20s  2.82%  std::__1::__atomic_base::fetch_xor (inline)
         0     0% 98.87%      0.20s  2.82%  std::__1::__atomic_base::operator^= (inline)
```

2.  multi thread with 1 other thread: `profiler3_unittest 100 1 profile1_t3.prof` 

```
File: profiler3_unittest
Type: cpu
Showing nodes accounting for 11.13s, 98.67% of 11.28s total
Dropped 11 nodes (cum <= 0.06s)
      flat  flat%   sum%        cum   cum%
     3.30s 29.26% 29.26%      7.60s 67.38%  test_main_thread
     1.71s 15.16% 44.41%      3.56s 31.56%  test_other_thread
     0.97s  8.60% 53.01%      4.01s 35.55%  _Printf
     0.86s  7.62% 60.64%      0.86s  7.62%  prout
     0.85s  7.54% 68.17%      0.85s  7.54%  [libc.so.5]
     0.80s  7.09% 75.27%      0.80s  7.09%  __memcpy_isr
     0.62s  5.50% 80.76%      0.62s  5.50%  _Mbtowcx
     0.39s  3.46% 84.22%      0.39s  3.46%  __c11_atomic_fetch_xor (inline)
     0.36s  3.19% 87.41%      0.58s  5.14%  _Putfld
     0.34s  3.01% 90.43%      0.34s  3.01%  _Mbtowc
     0.30s  2.66% 93.09%      5.66s 50.18%  snprintf
     0.21s  1.86% 94.95%      0.34s  3.01%  _Puttxt
     0.14s  1.24% 96.19%      0.14s  1.24%  _Litob
     0.13s  1.15% 97.34%      0.13s  1.15%  __memchr_isr
     0.09s   0.8% 98.14%      0.09s   0.8%  __strchr_isr
     0.06s  0.53% 98.67%      0.06s  0.53%  _get_arg_num (inline)
         0     0% 98.67%      7.69s 68.17%  _start
         0     0% 98.67%      7.68s 68.09%  main
         0     0% 98.67%      3.59s 31.83%  pthread_attr_setdetachstate
         0     0% 98.67%      0.39s  3.46%  std::__1::__atomic_base::fetch_xor (inline)
         0     0% 98.67%      0.39s  3.46%  std::__1::__atomic_base::operator^= (inline)
         0     0% 98.67%      3.59s 31.83%  std::__1::__function::__policy_func::operator() (inline)
         0     0% 98.67%      3.59s 31.83%  std::__1::__invoke (inline)
         0     0% 98.67%      3.59s 31.83%  std::__1::__thread_execute (inline)
         0     0% 98.67%      3.59s 31.83%  std::__1::__thread_proxy
         0     0% 98.67%      3.59s 31.83%  std::__1::function::operator() (inline)
```

3.  multi thread with 10 other threads: `profiler3_unittest 100 10 profile1_t3.prof` 

```
File: profiler3_unittest
Type: cpu
Showing nodes accounting for 43.30s, 97.96% of 44.20s total
Dropped 22 nodes (cum <= 0.22s)
      flat  flat%   sum%        cum   cum%
    17.04s 38.55% 38.55%     36.88s 83.44%  test_other_thread
        4s  9.05% 47.60%     15.09s 34.14%  _Printf
     3.41s  7.71% 55.32%      3.41s  7.71%  [libc.so.5]
     3.39s  7.67% 62.99%      3.39s  7.67%  __memcpy_isr
     3.16s  7.15% 70.14%      6.82s 15.43%  test_main_thread
     2.91s  6.58% 76.72%      2.91s  6.58%  _Mbtowcx
     2.37s  5.36% 82.08%      2.37s  5.36%  prout
     1.71s  3.87% 85.95%      1.71s  3.87%  _Mbtowc
     1.24s  2.81% 88.76%      1.24s  2.81%  __c11_atomic_fetch_xor (inline)
     1.08s  2.44% 91.20%      2.24s  5.07%  _Putfld
     0.87s  1.97% 93.17%     21.84s 49.41%  snprintf
     0.77s  1.74% 94.91%      1.28s  2.90%  _Puttxt
     0.60s  1.36% 96.27%      0.60s  1.36%  _Litob
     0.45s  1.02% 97.29%      0.45s  1.02%  __strchr_isr
     0.30s  0.68% 97.96%      0.30s  0.68%  __memchr_isr
         0     0% 97.96%      6.94s 15.70%  _start
         0     0% 97.96%      6.94s 15.70%  main
         0     0% 97.96%     37.26s 84.30%  pthread_attr_setdetachstate
         0     0% 97.96%      1.24s  2.81%  std::__1::__atomic_base::fetch_xor (inline)
         0     0% 97.96%      1.24s  2.81%  std::__1::__atomic_base::operator^= (inline)
         0     0% 97.96%     37.26s 84.30%  std::__1::__function::__policy_func::operator() (inline)
         0     0% 97.96%     37.26s 84.30%  std::__1::__invoke (inline)
         0     0% 97.96%     37.26s 84.30%  std::__1::__thread_execute (inline)
         0     0% 97.96%     37.26s 84.30%  std::__1::__thread_proxy
         0     0% 97.96%     37.26s 84.30%  std::__1::function::operator() (inline)
```

**Comment by alk** [comment]
Thanks. So this seems to prove that, indeed, "wallclock" time profiling has some value on QNX. Now the question is how it compares to it's stock profiling tools. I.e. why bother if (as far as I understand) QNX already has own profiling facility?

**Pull request closed without merging**
