### PR TITLE
Fix _aligned_realloc in WIN32_OVERRIDE_ALLOCATORS mode

### PR DESCRIPTION
**Pull request by HolyWu**

### CODE REVIEW

**Comment by alk** [comment]
Thanks again. Same here. Can you please add more details on why you're doing this?

**Comment by HolyWu** [comment]
No problem. _msize and _expand are called by _aligned_realloc internally. The added unit test would fail if both of them are not overridden. To avoid linker errors we override the *_base functions as well.

**Comment by alk** [comment]
Thanks for the patch, but somehow your new test actually fails under x86 (i.e. 32 bit) and release+patch mode.

**Comment by HolyWu** [comment]
I can reproduce it too. For unknown reason the call to `_aligned_realloc` causes an access violation under x86 when patching, but works fine under x64 as well as x86/x64 when overriding. Some mysteries here...

**Pull request closed without merging**
