### PR TITLE
fix cmake pthread complile

### PR DESCRIPTION
**Pull request by qqwangxiaow**
I think we need to add a dependency on pthread here.

### CODE REVIEW

**Comment by alk** [comment]
Hi. Thanks for the patch. But can you please elaborate what is the issue exactly that you're fixing here. What doesn't work without this patch ?

**Comment by qqwangxiaow** [comment]
> Hi. Thanks for the patch. But can you please elaborate what is the issue exactly that you're fixing here. What doesn't work without this patch ?

Description:	Debian GNU/Linux 9.8 (stretch)
Release:	9.8
gcc version 9.4.0

I have encountered this problem
make -j 8
image

**Comment by alk** [comment]
Thanks. it is clear now. But adding -lpthread is not the right fix. Some OSes don't have -lpthread. So I'll see what might be wrong.

P.S. Also for the later, please, consider learning how to quote regular text rather then posting screenshoots. Not as usable on mobile.

**Comment by alk** [comment]
See my commit linked above. Should be fixed now.

**Pull request closed without merging**
