### PR TITLE
Fix occasional crush on x86_64 environment

### PR DESCRIPTION
**Pull request by chen3feng**
Issue description:
With HEAPCHECK enabled environment, My program crash here occasionally.
```
// gperftools-2.4/src/stacktrace_x86-inl.h
 327       while (sp && n < max_depth) {
>328         if (*(sp+1) == reinterpret_cast<void *>(0)) {
 329           // In 64-bit code, we often see a frame that
 330           // points to itself and has a return address of 0.
 331           break;
 332         }

```   
with call stack
```
*** SIGSEGV (@0x7fff6e5999a8) received by PID 27560 (TID 0x7f2fa8fff9c0) from PID 1851365800; stack trace: ***
    @     0x7f2f94bbe710 (unknown)
    @     0x7f2f949a65d0 GetStackTrace_x86()
    @     0x7f2f949a6ba6 GetStackTrace()
    @     0x7f2f94df435a MallocHook_GetCallerStackTrace
    @     0x7f2f94e0669f HeapProfileTable::GetCallerStackTrace()
    @     0x7f2f94dfb593 NewHook()
    @     0x7f2f94df37fa MallocHook::InvokeNewHookSlow()
    @     0x7f2f9506dc39 operator new()

```
Analysis:
For performance reason, our gperftools was not configured with libunwinding,
and all our code compiled with -fno-omit-frame-pointer, but for system libraries such as glibc, we kept them unchanged, which are compiled with -fomit-frame-pointer by default. maybe it is the reason of crash.

Solution:
I noticed that msync was used in other paths to check the validity of pointer, but maybe because it is slow, It is not enabled in normal path.
So I provide an optimized implementation.

I've already signed CLA the several years ago, in the age of googlecode. so I'm glad to contribute this change.

### CODE REVIEW

**Comment by alk** [comment]
Hi. This is very interesting idea. But I think it won't work for signal handlers running on alternate stacks (i.e. sigaltstack).

Maybe instead of caching stack bottom, we can cache few recent results of msync?

Also I think we need to keep this code working on systems without functional __thread. config.h has define for whether TLS works, so I think you can just place ifdef around new code for TLS availability.

**Comment by chen3feng** [comment]
Thanks, I'll continue work on it.

**Comment by chen3feng** [comment]
Hi, I made a new change that avoided using thread local.
thank you for your review!

**Comment by alk** [comment]
Thanks. How about making it even faster by caching valid stacks? Something like that: https://github.com/alk/gperftools/tree/wip-safe-and-fast-frame-pointer-unwinding but cleaned up ? https://github.com/alk/gperftools/tree/wip-safe-and-fast-frame-pointer-unwinding

Also given you're effectively dropping STRICT_UNWINDING can you please clean it up from the code ?

**Comment by alk** [comment]
Hi. Do you still want this merged ?

**Comment by alk** [comment]
BTW, I've now replaced x86 stacktrace capturing method with generic-fp and it now (by default) msyncs every page access. It is careful not to test same page twice. But didn't get to more advanced caching means. Anyway, this commit is now out of date. Closing.

**Pull request closed without merging**
