### PR TITLE
code refactor#rewritten with WaitOnAddress for better performance.

### PR DESCRIPTION
**Pull request by shiyi23**
issue id: [1333](https://github.com/gperftools/gperftools/issues/1333)

### CODE REVIEW

**Comment by alk** [comment]
Thanks a lot! Looking. Do we need to "#include <synchapi.h>" ?

**Comment by alk** [comment]
Hm, the docs mention that it requires at least windows 8. And there are still some users of windows 7. So worth a think.

[1] https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-waitonaddress

[2] https://www.statista.com/chart/2322/market-share-of-desktop-operating-systems/#:~:text=According%20to%20estimates%20from%20Statcounter,points%20from%20a%20year%20earlier.

**Comment by alk** [comment]
Looking at what chrome does, I think we should keep support for win7. Can you do ifdef or something (getprocaddr perhaps to dynamically "probe" for waitonaddress ?)

**Comment by shiyi23** [comment]
> Looking at what chrome does, I think we should keep support for win7. Can you do ifdef or something (getprocaddr perhaps to dynamically "probe" for waitonaddress ?)

Thank you for your valuable comments! I'll keep optimizing this code!

**Comment by lennoxho** [comment]
> Looking at what chrome does, I think we should keep support for win7. Can you do ifdef or something (getprocaddr perhaps to dynamically "probe" for waitonaddress ?)

Make sure to do this binding during tcmalloc startup procedures to avoid the cost of checking each time SpinLockDelay is called.

**Comment by lennoxho** [comment]
Another thing we might want to consider is the performance on Windows 10 (ARM64).

**Comment by lennoxho** [comment]
Thanks for looking into this.
Sorry I didn't follow up on #1333. My company has a tedious FOSS contribution process.

**Comment by shiyi23** [comment]
> Thanks for looking into this. Sorry I didn't follow up on #1333. My company has a tedious FOSS contribution process.



> Thanks for looking into this. Sorry I didn't follow up on #1333. My company has a tedious FOSS contribution process.

No matter, I thank you very much, your work inspires me!

**Comment by lennoxho** [comment]
New PR attempt which addresses the comment to support Windows 7 or older.
https://github.com/gperftools/gperftools/pull/1438

**Comment by alk** [comment]
Thanks for the patch. We took the new proposed patch.

Let me also clarify what happened there. Since in this pull request I argued that we need to support win 7, while what we ended up taking is win8+ only.

The idea is _back then_ when this pull request was proposed, win7 was seemingly still supported by bunch of software as noted above. But today, win7 is pretty much abandoned by all major software packages. Thus decision to simplify.

**Pull request closed without merging**
