### PR TITLE
Log(n) page heap

### PR DESCRIPTION
**Pull request by toddlipcon**
Here's a PR for the work we've been discussing in issue #535. A few notes on the changes since your branch:
- rebased on 2.6.3
- updated the docs and the dot diagram
- changed the std::set<> to include a pair-like structure which caches the length inline. As discussed this was about a 10% boost in the micro-benchmark.
- changed ReleaseAtLeastNPages to release the smallest large spans rather than the largest
- changed to use memcpy in SpanSetRevPtr instead of type-punning to avoid potential aliasing analysis bugs
- moved the STLPageHeapAllocator to page_heap_allocator.h since it is generic and not span-specific
- some cleanup of comments, added docs to new code, etc.
- updated commit message
- left a non-functional change in one of the tests as a memorial to James Golick who passed away while previously working on this issue, hope that's OK

### CODE REVIEW

**Comment by toddlipcon** [comment]
I got a chance to test this on a particular Kudu workload that currently performs a lot of large allocations. It sped up the end-to-end workload by about 4x (AllocLarge was previously the top CPU consumer and also substantially limited concurrency).

Prior to patch YCSB stats line:
2018-02-22 00:07:38:535 230 sec: 4210774 operations; 19183.4 current ops/sec; est completion in 1 hours 27 minutes [READ: Count=191832, Max=53311, Min=283, Avg=6668.16, 90=16831, 99=20671, 99.9=41663, 99.99=49407, COAvg=7842.57, CO90=14727, CO99=21487, CO99.9=40191, CO99.99=47519] 

Post-patch:
2018-02-22 00:18:35:197 170 sec: 12910836 operations; 86968.3 current ops/sec; est completion in 19 minutes [READ: Count=869682, Max=137599, Min=281, Avg=1469.48, 90=2769, 99=5495, 99.9=23439, 99.99=117567, COAvg=2724.41, CO90=3487, CO99=30863, CO99.9=113919, CO99.99=129151] 

(4.5x throughput, 6x better 90p latency)

This is a workload we don't optimize much more (we probably would spend more effort to avoid large allocations if we did) but it's still a very nice win. I'll probably patch this PR into our local build of tcmalloc before our next release given the above results.

**Comment by alexeyserbin** [comment]
Attached is a tiny additional patch that fixes build on MacOS X (v 10.13 a.k.a. High Sierra).  Without the patch, the build-time checks enforced by the C++ compiler from the dev toolchain lead to errors like below:

```
    In file included from gperftools-2.6.3/src/central_freelist.cc:36:
    In file included from gperftools-2.6.3/src/central_freelist.h:45:
    In file included from gperftools-2.6.3/src/span.h:40:
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/set:412:5: error:
          static_assert failed "Allocator::value_type must be same type as
          value_type"
        static_assert((is_same<typename allocator_type::value_type, value_type>::value)
```

[gperftools.diff.txt](https://github.com/gperftools/gperftools/files/1755193/gperftools.diff.txt)

**Comment by alk** [comment]
Merged. Thanks a lot!

I added couple fixes on top of MS Visual Studio. "Less" operator needed to be const and somehow MSVC needs operator != for allocator as well.

I also added separate commit that refactored span set iterator treatment. Please have a look and let me know what you think.

**Comment by toddlipcon** [comment]
Took a look at your commit for the SpanSet iterator. Seems fine to me. Thanks for merging!

**Comment by alk** [comment]
Hm, I haven't spotted that OSX patch was not from Todd. I apologize for not referring to his contribution in commit. I'll make sure release notes will mention his work. Thanks Alexey.

**Pull request closed without merging**
