### PR TITLE
Mark malloc extension allocation as ignored for the LeakSanitizer

### PR DESCRIPTION
**Pull request by romange**

### CODE REVIEW

**Comment by romange** [comment]
Calms "-fsanitize=address" mode

**Comment by alk** [comment]
Thanks for patch and apologies for slow reaction. This looks sensible. Can you please combine all the patches ?

**Comment by romange** [comment]
Hi @alk. Github has squash and merge option. It's not the same?

**Comment by alk** [comment]
I want nice and sensible commit message. Github whatever thingy is likely to make it crap.

Ah, another thing for commit specifically. windows doesn't have "weak" AFAIR. But lsan might still be useful there. We'll probably want to ifdef this somehow.

**Comment by romange** [comment]
@alk  Unfortunately, I do not have windows build to verify this patch. I've applied the requested fixes.

**Comment by romange** [comment]
Hi @alk, ptal

**Comment by romange** [comment]
Hi @alk , is something wrong with the PR ?

**Comment by alk** [comment]
I need some more time. Thing about weak attribute is it doesn't change anything for shared libraries. So then link order determines which function actually gets used. Stuff specified earlier on command line (or implicitly) usually gets precedence. So we'll need to check if libtcmalloc.so could actually override lsan's function. Which would be undesirable.

**Comment by alk** [comment]
Also looks like weak is not really supported on OSX. Eh...

**Comment by romange** [comment]
I guess this change brings more work than value :D. It was meant for
convenience, we can drop it.

**Pull request closed without merging**
